global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
#  - job_name: 'snpdata'
#    metrics_path: '/metrics/192.168.90.23/9089'  # Apply metrics path at the job level
#    static_configs:
#      - targets: ['192.168.90.102:8080']  # First target

  - job_name: 'snpdata'  # Separate job if you need a different metrics path
    metrics_path: '/metrics/192.168.90.23/9089'  # Different metrics path
    static_configs:
      - targets: ['192.168.90.102:8080']  # Second target


remote_write:
  - url: '<Your Prometheus remote_write endpoint>'
    basic_auth:
      username: '<Your Grafana Username>'
      password: '<Your Grafana Cloud Access Policy Token>'
