name: snp_exporter docker image

on: 
	push:
		branches:
			"main"

jobs:
	build:
		name: Build Docker image
		runs-on: ubuntu-latest # specify the build machine
		steps:
			- # checkout to the repository on the build machine
				name: Checkout
				uses: actions/checkout@v3
			- # login to Docker Hub using the secrets provided
				name: Login to Docker Hub
				uses: docker/login-action@v2
				with:
					username: $
					password: $
			- # create a build kit builder instance
				name: Set up Docker Buildx
				uses: docker/setup-buildx-action@v2
			- # build the container image and push it to Dockerhub
				name: Build and push
				uses: docker/build-push-action@v4
				with:
					context: .
					file: ./Dockerfile
					push: true
					tags: $/snp_exporter:latest
